### ISSUE TITLE
Purpose not clear

### ISSUE THREAD

**Issue by heyvidy** [AdusparxAdith/Python#1]
https://github.com/AdusparxAdith/Python/blob/dc8dbf896b2262141c7bf6f9f5e1e88f8dfddc40/DeleteImages.py#L27-L36

I notice that most of the code you've written is pretty straightforward. But the lines I've highlighted don't make as much sense as to what they are doing. Was that part of your practice/test code, if yes, you can get rid of it. Else, use comments to explain it. 

Also, it's a good rule of thumb to have documentation included with the code. So please add comments wherever necessary.

**Comment by AdusparxAdith** [comment]
Hey thanks for the feedback! I thought counting the number of files would be handy if there were a lot of files in the target folder.
I thought I could add like a "there are more files, do you want to delete more?" option.  

And I'll definitely add comments from now onwards, thanks!
